builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
