builds:
  - ldflags: -s -w -X main.commit={{.Commit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archive:
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md
