[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "=1.12.9"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "=0.8.0"

[[constraint]]
  name = "github.com/kylelemons/godebug"
  revision = "d65d576e9348f5982d7f6d83682b694e731a45c6"

[[constraint]]
  branch = "master"
  name = "github.com/jehiah/go-strftime"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "github.com/ivpusic/grpool"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"
